/**
 * B.Tech course catalog with scheduled times for the academic year.
 * Used on the Courses page for both students and faculty.
 */
export const BTECH_COURSES = [
  {
    code: "CS101",
    name: "Data Structures and Algorithms",
    description: "Fundamental data structures including arrays, linked lists, stacks, queues, trees, and graphs. Algorithm design and analysis using Big-O notation.",
    day: "Mon, Wed",
    time: "09:00 – 10:30",
    duration: "14 weeks",
    semester: "III",
    credits: 4,
  },
  {
    code: "CS102",
    name: "Database Management Systems",
    description: "Relational model, SQL, normalization, transaction processing, and database design. Introduction to NoSQL and distributed databases.",
    day: "Tue, Thu",
    time: "10:45 – 12:15",
    duration: "14 weeks",
    semester: "IV",
    credits: 4,
  },
  {
    code: "CS103",
    name: "Operating Systems",
    description: "Process scheduling, memory management, file systems, and concurrency. Hands-on with shell scripting and system calls.",
    day: "Mon, Wed",
    time: "14:00 – 15:30",
    duration: "14 weeks",
    semester: "V",
    credits: 4,
  },
  {
    code: "CS104",
    name: "Computer Networks",
    description: "OSI and TCP/IP models, protocols, routing, and network security. Socket programming and network simulation.",
    day: "Tue, Fri",
    time: "09:00 – 10:30",
    duration: "14 weeks",
    semester: "V",
    credits: 4,
  },
  {
    code: "CS105",
    name: "Software Engineering",
    description: "SDLC, requirements analysis, design patterns, testing, and project management. Agile and DevOps practices.",
    day: "Thu, Fri",
    time: "11:00 – 12:30",
    duration: "14 weeks",
    semester: "VI",
    credits: 4,
  },
  {
    code: "CS106",
    name: "Machine Learning",
    description: "Supervised and unsupervised learning, regression, classification, and neural networks. Applications using Python and common frameworks.",
    day: "Mon, Thu",
    time: "15:45 – 17:15",
    duration: "14 weeks",
    semester: "VII",
    credits: 4,
  },
  {
    code: "CS107",
    name: "Artificial Intelligence",
    description: "Search algorithms, knowledge representation, reasoning, and intelligent agents. Introduction to NLP and computer vision.",
    day: "Wed, Fri",
    time: "14:00 – 15:30",
    duration: "14 weeks",
    semester: "VII",
    credits: 4,
  },
  {
    code: "MA101",
    name: "Engineering Mathematics I",
    description: "Calculus, linear algebra, and differential equations. Applications to engineering problems.",
    day: "Tue, Thu",
    time: "08:00 – 09:30",
    duration: "14 weeks",
    semester: "I",
    credits: 4,
  },
  {
    code: "MA102",
    name: "Engineering Mathematics II",
    description: "Advanced calculus, probability, and statistics. Fourier series and numerical methods.",
    day: "Mon, Wed",
    time: "08:00 – 09:30",
    duration: "14 weeks",
    semester: "II",
    credits: 4,
  },
  {
    code: "EC101",
    name: "Digital Logic Design",
    description: "Boolean algebra, combinational and sequential logic, and finite state machines. Introduction to HDL.",
    day: "Wed, Fri",
    time: "10:45 – 12:15",
    duration: "14 weeks",
    semester: "III",
    credits: 4,
  },
];
