export const DEPARTMENTS = [
  "Artificial Intelligence & Data Science (AI & DS)",
  "Bio-Technology / Biotechnology",
  "Civil Engineering",
  "Computer Science and Engineering (CSE)",
  "Computer Science and Information Technology (CS & IT)",
  "Electrical and Electronics Engineering (EEE)",
  "Electronics and Communication Engineering (ECE)",
  "Electronics and Computer Science / Engineering (ECS / ECSE)",
  "Internet of Things (IoT)",
  "Mechanical Engineering",
  "Architecture (B.Arch.)",
  "Computer Applications (BCA / MCA)",
  "Science Streams (e.g., Computer Science, Data Science, Food Technology, Applied Mathematics, Physics, Chemistry)",
  "Business Administration (BBA, MBA)",
  "Commerce (B.Com & M.Com)",
  "Law (LLB, LLM, Integrated Law)",
  "Hotel Management / Hospitality",
  "Fine Arts / Visual Communication",
  "Agriculture Science (B.Sc Agriculture)",
  "Pharmacy (B.Pharm / D.Pharm / M.Pharm)",
  "Other",
];
